### ISSUE TITLE
Add custom deployment `.spec.revisionHistoryLimit` support

### ISSUE THREAD

**Issue by yahel2410** [companyinfo/helm-charts#15]
First, great lib chart :star: 

Currently there is way to override the default deployment `.spec.revisionHistoryLimit`, which is set to 10 by default.
Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit

It would be great if this could be added as a custom value.

**Comment by p-afraz** [comment]
Hi thanks for your feedback 💯 
This will be included in next release.

**Comment by yahel2410** [comment]
Hey @p-afraz any ETA for the new version? :)
