### ISSUE TITLE
feature-request: allow to override envVars in a umbrella chart

### ISSUE THREAD

**Issue by 3deep5me** [companyinfo/helm-charts#19]
Hello,

i would like to override envVars if i use a Chart, which is created with helmet, as a Subchart.

E.g. i have a helmet chart for nginx where i configurated the the default listing-port on port 8080. I want to override this envv with the value 8088.

Right now if i does this, all other (default) envv which are also part of the subchart are removed from the deployment.

This would make its helmet charts usable as subcharts for me.

**Comment by atkrad** [comment]
Hello @3deep5me,

The underlying reason for this issue stems from the data type of `envVars`, which is currently defined as an `array`. Consequently, it's not possible to selectively update specific variables within it, as any modifications would lead to overwrites by a sub-chart. To address this limitation, we intend to redefine `envVars` as a `map`, which will provide us with the necessary flexibility.

In the foreseeable future, we have plans to incorporate this enhanced functionality. It is our expectation that you will be able to utilize this feature effortlessly once it is implemented.

**Comment by zevisert** [comment]
This should be closed by #24, you can now define envVars as an array or as a map, and helmet ^0.10.0 will render them correctly. 

Of course, you should be consistent in your chart and subcharts with which datastructure you are using. Helm should warn you if an envVar array is replaced with a map
